import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-table-component',
  templateUrl: './table-component.component.html',
  styleUrls: ['./table-component.component.css']
})
export class TableComponentComponent implements OnInit {

  headers = ["Hora","Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"]

  rows = [
    {"Hora" : "8:00",
    "Lunes" : "-",
    "Martes" : "-",
    "Miercoles" : "-",
    "Jueves" : "-",
    "Viernes" : "-",
    "Sabado" : "-"},
    {"Hora" : "8:30",
    "Lunes" : "-",
    "Martes" : "-",
    "Miercoles" : "-",
    "Jueves" : "-",
    "Viernes" : "-",
    "Sabado" : "-"},
    {"Hora" : "9:00",
    "Lunes" : "-",
    "Martes" : "-",
    "Miercoles" : "-",
    "Jueves" : "-",
    "Viernes" : "-",
    "Sabado" : "-"},
    {"Hora" : "9:30",
    "Lunes" : "-",
    "Martes" : "-",
    "Miercoles" : "-",
    "Jueves" : "-",
    "Viernes" : "-",
    "Sabado" : "-"},
    {"Hora" : "10:00",
    "Lunes" : "-",
    "Martes" : "-",
    "Miercoles" : "-",
    "Jueves" : "-",
    "Viernes" : "-",
    "Sabado" : "-"},
    {"Hora" : "10:30",
    "Lunes" : "-",
    "Martes" : "-",
    "Miercoles" : "-",
    "Jueves" : "-",
    "Viernes" : "-",
    "Sabado" : "-"},
    {"Hora" : "11:00",
    "Lunes" : "-",
    "Martes" : "-",
    "Miercoles" : "-",
    "Jueves" : "-",
    "Viernes" : "-",
    "Sabado" : "-"},
    {"Hora" : "11:30",
    "Lunes" : "",
    "Martes" : "",
    "Miercoles" : "",
    "Jueves" : "",
    "Viernes" : "",
    "Sabado" : ""},
    {"Hora" : "12:00",
    "Lunes" : "",
    "Martes" : "",
    "Miercoles" : "",
    "Jueves" : "",
    "Viernes" : "",
    "Sabado" : ""},
    {"Hora" : "12:30",
    "Lunes" : "",
    "Martes" : "",
    "Miercoles" : "",
    "Jueves" : "",
    "Viernes" : "",
    "Sabado" : ""},
    {"Hora" : "13:00",
    "Lunes" : "",
    "Martes" : "",
    "Miercoles" : "",
    "Jueves" : "",
    "Viernes" : "",
    "Sabado" : ""},
    {"Hora" : "13:30",
    "Lunes" : "",
    "Martes" : "",
    "Miercoles" : "",
    "Jueves" : "",
    "Viernes" : "",
    "Sabado" : ""},
    {"Hora" : "14:00",
    "Lunes" : "",
    "Martes" : "",
    "Miercoles" : "",
    "Jueves" : "",
    "Viernes" : "",
    "Sabado" : ""},
    {"Hora" : "14:30",
    "Lunes" : "",
    "Martes" : "",
    "Miercoles" : "",
    "Jueves" : "",
    "Viernes" : "",
    "Sabado" : ""},
    {"Hora" : "15:00",
    "Lunes" : "",
    "Martes" : "",
    "Miercoles" : "",
    "Jueves" : "",
    "Viernes" : "",
    "Sabado" : ""},
    {"Hora" : "15:30",
    "Lunes" : "",
    "Martes" : "",
    "Miercoles" : "",
    "Jueves" : "",
    "Viernes" : "",
    "Sabado" : ""},
    {"Hora" : "16:00",
    "Lunes" : "",
    "Martes" : "",
    "Miercoles" : "",
    "Jueves" : "",
    "Viernes" : "",
    "Sabado" : ""},
    {"Hora" : "16:30",
    "Lunes" : "",
    "Martes" : "",
    "Miercoles" : "",
    "Jueves" : "",
    "Viernes" : "",
    "Sabado" : ""}
  ]

  constructor() { }

  ngOnInit() {
  }

}
